# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bikes', '0022_auto_20160915_1716'),
        ('shopping_cart', '0002_auto_20160915_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bikes.Bikes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bikes.Order')),
            ],
        ),
    ]
