# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-01 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0003_auto_20160801_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bikes.Order'),
        ),
        migrations.AddField(
            model_name='card',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bikes.Order'),
        ),
        migrations.AddField(
            model_name='preorders',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bikes.Billing'),
        ),
        migrations.AddField(
            model_name='preorders',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bikes.Card'),
        ),
    ]
