# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0006_auto_20160801_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='preorders',
            name='payment',
        ),
    ]
