# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0008_auto_20160801_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='user_info',
            field=models.CharField(max_length=101),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_info',
            field=models.CharField(max_length=101),
        ),
    ]
