# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0012_auto_20160805_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user_info',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user_info',
        ),
    ]
