# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0013_auto_20160805_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='user',
            new_name='user_info',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='user_info',
        ),
    ]
