# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0015_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.CharField(default='from', max_length=25),
        ),
    ]
