# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0016_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biketypes',
            name='picture',
            field=models.ImageField(height_field=50, upload_to='', width_field=50),
        ),
    ]
