# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0018_auto_20160907_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bikes.Bikes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bikes.Order')),
            ],
        ),
    ]
